### PR TITLE
Update to run on x86

### PR DESCRIPTION
**Pull request by elvece**

### CODE REVIEW

**Comment by elvece** [comment]
Proof:

```
root@embassy-<redacted>:/home/start9# docker exec -it photoview.embassy /bin/bash
root@photoview:/app# uname -a
Linux photoview.embassy 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 x86_64 GNU/Linux
```

**Comment by elvece** [comment]
@islandbitcoin is it expected to see this page? 
Screen Shot 2022-10-10 at 5 23 02 PM

It throws errors when populated, also tried with photo path as just `/photos`:

Screen Shot 2022-10-10 at 5 39 13 PM

Relevant Logs:
```
2022-10-10T17:38:07-06:00  2022/10/10 23:38:07 /app/graphql/models/user.go:118 ERROR: duplicate key value violates unique constraint "users_username_key" (SQLSTATE 23505)
2022-10-10T17:38:07-06:00  [40.964ms] [rows:0] INSERT INTO "users" ("created_at","updated_at","username","password","admin") VALUES ('2022-10-10 23:38:07.715','2022-10-10 23:38:07.715','admin','$2a$12$4mNe9Oybe4rwmFbSvi4FvOOPrV0pINer5DuZh3VudxwhLLtVN95Ta',true) RETURNING "id"
2022-10-10T17:38:07-06:00  runtime error: invalid memory address or nil pointer dereference
```
Full logs (change the file extension to `.html`, which can't be uploaded in a GH comment:
[photoview-logs.md](https://github.com/Start9Labs/photoview-wrapper/files/9749814/photoview-logs.md)

**Comment by islandbitcoin** [comment]
You should definitely not see that page. Are you trying to install over an existing install of the same version#?

**Comment by islandbitcoin** [comment]
This line in the docker_entrypoint should be taking care of that:

  INFO_UPDATE="update site_info set initial_setup = false;"

**Comment by elvece** [comment]
> You should definitely not see that page. Are you trying to install over an existing install of the same version#?

Updates worked fine. It was a fresh install where this expressed. I believe this to be a result of emulation - that the time between setting up the database and updating values was too long. Increasing the sleep value resolved.

**Pull request merged**
